// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinaisPeloMundo.Data;

#nullable disable

namespace SinaisPeloMundo.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SinaisPeloMundo.Models.ClienteModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.InterpreteModel", b =>
                {
                    b.Property<int>("InterpreteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeInterprete")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoDiaria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("InterpreteId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Interpretes");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PacoteModel", b =>
                {
                    b.Property<int>("PacoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InterpreteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassagemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservaHotelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("PacoteId");

                    b.HasIndex("InterpreteId");

                    b.HasIndex("PassagemId")
                        .IsUnique();

                    b.HasIndex("ReservaHotelId")
                        .IsUnique();

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PassagemModel", b =>
                {
                    b.Property<int>("PassagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HorarioChegada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HorarioPartida")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalChegada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPartida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacaTransporte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Poltrona")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPassagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PassagemId");

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PedidoModel", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEfetivacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PacoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parcelas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PacoteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.ReservaHotelModel", b =>
                {
                    b.Property<int>("ReservaHotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCheckout")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoHotel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeHotel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservaHotelId");

                    b.ToTable("Hoteis");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PacoteModel", b =>
                {
                    b.HasOne("SinaisPeloMundo.Models.InterpreteModel", "Interprete")
                        .WithMany("Pacotes")
                        .HasForeignKey("InterpreteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaisPeloMundo.Models.PassagemModel", "Passagem")
                        .WithOne("Pacote")
                        .HasForeignKey("SinaisPeloMundo.Models.PacoteModel", "PassagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaisPeloMundo.Models.ReservaHotelModel", "ReservaHotel")
                        .WithOne("Pacote")
                        .HasForeignKey("SinaisPeloMundo.Models.PacoteModel", "ReservaHotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interprete");

                    b.Navigation("Passagem");

                    b.Navigation("ReservaHotel");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PedidoModel", b =>
                {
                    b.HasOne("SinaisPeloMundo.Models.ClienteModel", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaisPeloMundo.Models.PacoteModel", "Pacote")
                        .WithMany("Pedidos")
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.ClienteModel", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.InterpreteModel", b =>
                {
                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PacoteModel", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.PassagemModel", b =>
                {
                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("SinaisPeloMundo.Models.ReservaHotelModel", b =>
                {
                    b.Navigation("Pacote");
                });
#pragma warning restore 612, 618
        }
    }
}
